README.md, docs/RelayAPI.md, relay/app.py, relay/node.py, relay/resources.py
-Fix balance endpoint 
-change endpoints to only return single value not wrapped in an object
-update documentation
=> Fix balance endpoint 

relay/api/app.py, relay/api/messaging/resources.py, relay/api/streams/app.py, relay/api/streams/rpc_methods.py, relay/api/streams/transport.py, relay/blockchain/events.py, relay/events.py, relay/main.py, relay/network_graph/graph.py, relay/streams.py, tests/unit/test_streams.py
Add post message endpoint
Add stream messages websocket
Closes #59
=> Add messaging

README.md, docs/RelayAPI.md
Closes #83 
- updates REST API documentation of relay
- does not include exchange endpoints
=> Update API docs

relay/network_graph/dijkstra_weighted.py, relay/network_graph/graph.py, tests/unit/test_graph.py
See issue: https://github.com/trustlines-network/relay/issues/32
=> Added function to find 'triangulation path', sending money to one's self

relay/api/app.py
In rare cases it could happen that the resulting error message from an exception was printed with the default error page. Now this should always result in a json message.
Also there was a bug with the image and dump endpoints of a network
=> Add default json error handler for exceptions

relay/pushservice/client.py, relay/pushservice/client_token_db.py, relay/pushservice/pushservice.py, relay/relay.py
Send push notifications when events happen  …
Add integration into event subjects
Add methods to add and remove client tokens for push notifications
Closes #112
Builds on top of #113, so merge that first
=>  Send push notifications when events happen

relay/api/app.py, relay/api/pushservice/resources.py, relay/pushservice/pushservice.py, relay/relay.py
Add REST endpoints to add and delete client tokens  …
Closes #111
builds on top of #114, so merge that first
=> Add REST endpoints to add and delete client tokens

relay/pushservice/pushservice.py
other events will only be sent as messages because the users
does not need a notification for that
closes #121
=> Only send some events as push notification

relay/api/exchange/resources.py, relay/api/exchange/schemas.py, relay/api/fields.py, relay/exchange/order.py
The signature was sometimes to short and was in upper case
closes #138
=> Fix signature length and case

tests/chain_integration/conftest.py
to fix the tests to work after merging https://github.com/trustlines-network/contracts/pull/111
=> Fix tests to run with new deploy commandline scrips

docs/RelayAPI.md, relay/api/app.py, relay/api/resources.py
endpoint corresponding to https://github.com/trustlines-network/relay/pull/117#discussion_r199435784
https://github.com/trustlines-network/relay/issues/34
=> added enpoint for max capacity path

tests/unit/api/exchange/test_schema.py
=> Add missing order schema tests

relay/api/app.py, relay/api/exchange/resources.py
Fix a bug in orderbook, that the orderbook was not returned in the right format
This was because.data was missing
Fix another bug in error handling that happend because we upgraded webargs to a new version
=> Fix a bug in orderbook

relay/exchange/exchange_db.py, relay/relay.py
Use BigInteger for now. This might not be enough, but Ill open another issue. 
Closes #133
=> Connect DEX and client token db to postgres database.

docker/trustlines/.env, docker/trustlines/.gitignore, docker/trustlines/README.md, docker/trustlines/addresses.json, docker/trustlines/config.json, docker/trustlines/docker-compose.yml
This adds a docker-compose based setup and is part of
https://github.com/trustlines-network/relay/issues/140
=> add docker-compose based setup

relay/api/streams/transport.py, relay/pushservice/client.py, relay/streams.py, tests/unit/test_streams.py
The client keeps a list of subscriptions now so that we can stop listening if the connection is closed
closes #86
=> Add internal unsubscription if we know the websocket has disconnected

Dockerfile, README.md, docs/RelayServer.md, relay/api/tokens/resources.py, relay/blockchain/currency_network_proxy.py, relay/blockchain/proxy.py, relay/ethindex_db.py, relay/relay.py, relay/streams.py, relay/utils.py, setup.py
Removed type hintings in comments and now use variable type annotations
Closes #136
=> Update to python 3.6

.travis.yml, constraints.txt, requirements.txt, setup.cfg
Add coverage report
Add distributed test run
This add codecov reports, what do you think?
=> Improve test run

.travis.yml
setuptools_scm doesn't work otherwise.
=> travis: don't use shallow clone

Dockerfile, README.md, docs/RelayServer.md, relay/api/tokens/resources.py, relay/blockchain/currency_network_proxy.py, relay/blockchain/proxy.py, relay/ethindex_db.py, relay/relay.py, relay/streams.py, relay/utils.py, setup.py
Need to revert because web3 v3 requieres old version of gevent which is not compatible with python 3.6
This reverts commit e2e34e852e954826f8a6f7270b11308d456819e2.
Closes #172
=> Revert "Update to python 3.6"

relay/api/messaging/resources.py, relay/api/schemas.py, relay/api/streams/rpc_methods.py, relay/api/streams/transport.py, relay/events.py, relay/pushservice/client.py, relay/pushservice/pushservice.py, relay/relay.py, relay/streams.py, tests/unit/test_streams.py
Add type field in payload to give a hint to relay for pushnotification
Use MessageEvent internally
Listen for messages also as pushnotification client.
Closes #170
=>  Add paymentrequest over pushnotification

relay/relay.py
It will be the case for a while that we dont have an exchange. This PR enables to not have to provide an exchange.
=> Handle cases where part of address.json is missing

Dockerfile
Rather just use a build and a final image. We can remove debian cache files that
way.
Also don't install development dependencies (added the call to sed).
=> get rid of base image

relay/api/schemas.py
=> Remove deprecated address field

docs/RelayAPI.md, relay/api/resources.py, relay/api/schemas.py
Should be backwards compatible as I did not remove the old field.
=> Add field user and counterParty for consistency with events

docs/RelayAPI.md, relay/api/app.py, relay/api/resources.py
=> Remove old outdated endpoints to query spendable amount

relay/blockchain/node.py
This enables a more up to date nonce information. It will use the pending block to determine the next nonce or on parity it will use the nextNonce function that also includes the pending transactions. At the moment it will always default to parity, as we only use parity anyways. This also requires that the parity api is enabled (--jsonrpc-apis=all or --jsonrpc-apis=parity)
I checked that the e2e tests are still working. To fully test if that now allows to send faster transfers, we need to test it on the staging setup with the app. 
Closes https://github.com/trustlines-network/project/issues/176
=> Query the nonce from pending transactions

relay/blockchain/node.py
Increase the request eth threshold to 5
=> Increase requestEth threshold

relay/api/exchange/resources.py, relay/api/resources.py, relay/api/tokens/resources.py, relay/relay.py
Add more usage of dump_result_with_schema
Closes #215
=> Refactor api dumping

relay/network_graph/trustline_data.py
=> Document trustline data accessors

relay/relay.py
get_account_sum otherwise uses the current time and since we call multiple times
into this function, TrustlinesRelay may generate events based on different
timestamps.
While I'm here, also try to be a bit more functional and separate event creation
from publishing the events to the subscribers.
see https://github.com/trustlines-network/relay/issues/222
=> pass timestamp to get_account_sum functions from TrustlinesRelay

docs/RelayAPI.md, relay/api/resources.py
Also add the return of `value` in the doc since it is actually returned.
=> Change the return of api from `fee_payer` to `feePayer`

docs/RelayAPI.md
=> Change the type in the docs from address to string

docs/RelayAPI.md
closes https://github.com/trustlines-network/relay/issues/288
=> Add balance api in docs

relay/network_graph/graph.py, tests/unit/network_graph/test_graph.py
closes https://github.com/trustlines-network/relay/issues/285
=> Edge with negative capacity are not accounted for anymore

relay/api/exchange/resources.py, relay/pushservice/pushservice.py
Fix push notifications not working because of marshmallow upgrade.
After marshmallow upgrade we now not longer need to use .data
=> Fix pushnotifications not working

relay/api/resources.py, relay/relay.py
closes https://github.com/trustlines-protocol/relay/issues/345
=> Prevent asking for a path in a frozen currency network

tests/unit/network_graph/test_graph.py, tests/unit/network_graph/test_interests.py
This reverts commit f18424f4d6309ce059edbe3eda1570a5d08bda33 (PR
I accidentally pushed this PR and didn't notice it broke the CI setup.
=> Revert "Fix 'from tests' imports"

relay/api/resources.py, relay/blockchain/delegate.py, tests/chain_integration/test_delegate.py
closes https://github.com/trustlines-protocol/relay/issues/351
=> Add fee validation to send signed meta transaction

docs/RelayAPI.md
=> Align tables

docs/RelayAPI.md, src/relay/api/app.py, src/relay/api/resources.py, src/relay/api/schemas.py
This is based on PR #384. Please only review the last two commits.
This implements #375.
=> List all trustlines

tests/gen_testdata.py
Also fix issues when running the program with a non-dev chain. We need
to wait for transactions to finish in that case.
=> Adapt gen_testdata.py to new function signatures

setup.py, src/relay/boot.py, src/relay/main.py
This provides useful information while debugging. Add relay.boot
module, similar to the bridge's boot module.
=> Log the current greenlet

Dockerfile, README.rst, constraints.txt, docs/RelayServer.md, requirements.txt, setup.py
It doesn't look like it's still being.
=> Remove pygraphviz

src/relay/pushservice/pushservice.py
To be sure that the information shown in the app comes from the
connected relay server and not from push notifications, we remove the
data content. This might be added later again, to allow to at least send
the user to the right page in the app.
Also messages should only be sent out based on the underlying event and
does not depend on the message text.
=> Remove data content of push notification

src/relay/api/resources.py, src/relay/blockchain/delegate.py, tests/chain_integration/test_delegate.py
closes: https://github.com/trustlines-protocol/relay/issues/401
=> Provide more information on invalid meta-tx error message

docker/trustlines/config.toml
=> Update example relay config for docker-compose

docs/RelayAPI.md, src/relay/api/app.py, src/relay/api/resources.py, src/relay/api/schemas.py, src/relay/blockchain/node.py, tests/chain_integration/test_node.py
=> Add function in node to get tx status

docker/trustlines/README.md, docs/RelayServer.md
=> Add documentation how to get contracts.json file

.circleci/config.yml
=> Upload DockerHub release for version tags

src/relay/api/app.py, src/relay/api/fields.py, src/relay/api/resources.py, src/relay/api/schemas.py, src/relay/blockchain/node.py
Also remove dependency on MetaTransactionStatus of TransactionStatus
=> Fix the /transactions/status endpoint url missing `/`

src/relay/api/resources.py
closes https://github.com/trustlines-protocol/relay/issues/460#issuecomment-603960747
=> Remove unusued address field of account summary

src/relay/blockchain/proxy.py
=> Use latest instead pending block for event updates

requirements.txt, setup.py
Downgrade firebase-admin, as the upgrade caused issues.
Fix #481
=> Downgrade firebase-admin back to 2.x

src/relay/api/streams/transport.py
Because of a change in tinytpc we were sending bytes over the websocket,
which the other end could not handle properly. This was not an issue in
nodejs but in other environments, thats why we could not see this in the
e2e tests. Fixed by decoding it back to a string before sending it.
=> Fix send str again over websocket

src/relay/pushservice/pushservice.py
They changed following firebase admin sdk  version 3
https://firebase.google.com/docs/admin/migrate-python-v3
=> Update the exceptions thrown by firebase in pushnotifications

config/addresses_laika.json, config/addresses_tlbc.json
You should start using these addresses in the app.
=> Update addresses of identity implementations in examples of addresses
