- relay/api/app.py
- relay/api/resources.py
- relay/api/schemas.py
- relay/api/streams/app.py
- relay/api/streams/rpc_methods.py
- relay/api/streams/rpc_protocol.py
- relay/api/streams/transport.py
- relay/blockchain/currency_network_events.py
- relay/blockchain/currency_network_proxy.py
- relay/blockchain/proxy.py
- relay/main.py
- relay/streams.py
- requirements.txt
- tests/chain_integration/test_currency_network.py
- tests/chain_integration/test_graph_integration.py
- tests/unit/test_streams.py
Add first draft of event stream over websockets. 
Use jsonrpc as protocol for the messages. 
Only method implemented so far is subscribe with parameters event and user, to subscribe to all events for a user. 
Currently implemented events: Update and requests of creditlines, trustlines and balances of trustlines, transfers
> Add first draft of event stream over websockets

- relay/api/resources.py
- relay/blockchain/currency_network_proxy.py
- relay/blockchain/proxy.py
Closes #68 
- spawns multiple greenlets now when fetching events from the blockchain
- response time lowered significantly using this approach (for some local tests the measurements were: `before -> ~ 2000ms`  `after -> 600ms`)
> Concurrent event fetching

- relay/main.py
- relay/relay.py
- tests/conftest.py
When starting tl-relay with a non-existent rpc.host configured in config.json,
_load_addresses will raise an exception and the greenlet started in
_start_listen_on_new_addresses will exit.
All of this happens without a single thing being logged:
,----
| 2018-05-29 22:27:40,941[INFO] trustlines: Starting relay server
| 2018-05-29 22:27:40,987[INFO] trustlines: Server is running on ('', 5000)
| 2018-05-29 22:27:40,999[INFO] relay: New network: 0x55bdaAf9f941A5BB3EacC8D876eeFf90b90ddac9
`----
So, we now catch errors, log them and let the greenlet retry after it's sleep
period.
Also log the parameters used for connecting to the RPC host.
> log errors from load addresses, do not fail silently

- relay/api/resources.py
- relay/blockchain/currency_network_proxy.py
We did run into errors on the production server. Some of the calls to get events
did timeout, and we ran into errors because the code didn't handle that case.
gevent.joinall returns the list of finished greenlets, but most of the code
tried to collect results from all of the greenlets.
> fix usage of gevent.joinall, increase timeouts

- docs/RelayAPI.md
- relay/api/app.py
- relay/api/resources.py
I don't know why we have cost*2 here : https://github.com/trustlines-network/relay/blob/feature/debt-reduce-endpoint/relay/api/resources.py#L391
I only copied the Path class above, but I do not mind having cost*2 as it is only for checking gas price.
I do repeat myself but I do not know if that matters for api.
> added endpoint for debt reduce

- config.json
- relay/api/resources.py
- relay/blockchain/currency_network_proxy.py
- relay/blockchain/proxy.py
- relay/concurrency_utils.py
- relay/relay.py
- tests/unit/test_concurrency_utils.py
Add timeout as a config parameter
Add a concurrency joinall helper to make that functionality easy accessable
Check timeout only in outer most call in api
Instead of returning half of the events, return a timeout code.
> Use configurable timeouts in api

- constraints.txt
- requirements.txt
- setup.cfg
We install the following flake8 plugins:
- flake8-pep3101: warn about % formatting
- flake8-string-format: warn about errors in .format calls
- flake8-invalid-escape-sequences: warn about invalid escape sequences in
strings
and flake8-per-file-ignores in order to ignore warnings about % formatting in
one of our source files. flake8 automatically uses those plugins.
These should be pretty uncontroversial.
There are more useful plugins, but they either need work from our side to fix
things or need some discussion.
> install and use some useful flake8 plugins

- requirements.txt
- setup.py
Some dependencies had been missing in setup.py. Please not that setup.py depends
on trustlines-contracts, requirements.txt depends on git+https dependency for
that package. Installation of the former won't work, because the package doesn't
live on the public PyPI server.
> synchronize dependencies in setup.py and requirements.txt

- relay/streams.py
- tests/unit/test_streams.py
When inside notify calling client.send a client can unschedule the greenlet and thus delay unsubscription
inside of notify. This means it can be already unsubscribed and we have to handle that
> Fix a race condition bug in stream unsubscribe

- .pre-commit-config.yaml
- docs/RelayAPI.md
pre-commit [1] is framework for managing git pre-commit hooks. Since I failed to
reformat files with black before committing them in the past, let's try
this. Please note that we don't have any hooks for black enabled at the moment.
But it will run flake8 and do some more useful checks.
After installation of pre-commit, this can be activated by running
pre-commit install
also fix some things that it already complained about.
[1] https://pre-commit.com/
> add config file for pre-commit

- relay/api/resources.py
- relay/api/schemas.py
- relay/blockchain/node.py
- relay/network_graph/graph.py
Fixes #98
This also changes the txinfo endpoint. Balance is now returned as string and gasPrice also as string. 
nonce is still an Integer. 
@dakingha69 can you take a look what needs to change in the clientlib?
Also is it right to return it as strings in decimal format? What is the current most used variant in the ecospace. Hex encoded or decimal?
> Return values as strings

- .pre-commit-config.yaml
- constraints.txt
- relay/network_graph/dijkstra_weighted.py
- relay/network_graph/fees.py
- relay/network_graph/graph.py
- requirements.txt
- setup.cfg
- tests/unit/test_fees.py
- tests/unit/test_graph.py
https://github.com/trustlines-network/relay/issues/34
I added the function to find the max capacity path in dijkstra_weighted.py
I added the function to estimate the fees from the max capacity and the number of hops in fees.py, because I believe that is where it fits the most, and it would have to be changed if we change anything about the fees.
I added tests for the fee estimation in test_fees and tests for the path/capacity in graph.py
I later added tests showing that the max capacity path we found is actually usable in graph.py, these tests should fail in case someone comes to modify the fees without modifying the function to estimate the fees from the max capacity.
> Added functions to find max capacity path between source and target

- docs/RelayAPI.md
I would guess the implementation of the API does not match the documentation for "Transaction infos of user". The doc states "GET /users/:userAddress/tx-infos" while it is actually '/users/<address:user_address>/txinfos'.
https://github.com/trustlines-network/relay/blob/develop/relay/api/app.py#L65
See also: https://github.com/trustlines-network/clientlib/blob/develop/src/Transaction.ts#L140
> Change "tx-infos" to "txinfos" in api doc

- constraints.txt
- relay/api/schemas.py
- relay/blockchain/events.py
- relay/events.py
- tests/chain_integration/test_currency_network.py
- tests/unit/test_event.py
Add users own address as user in returned events
Change counter partys address from address into counterParty in returned events
Downgrade gevent as the new version broke web3 v3
Closes #130
> Include users own address in events

- relay/api/app.py
- relay/api/exchange/resources.py
- relay/blockchain/exchange_events.py
- relay/relay.py
- Adds endpoint `/exchange/users/<address:user_address>/events` for retrieving exchange events from all exchanges
- Also adds a comment on issue https://github.com/trustlines-network/py-eth-index/issues/16
> Exchange events endpoint for all exchanges

- docker/trustlines/docker-compose.yml
please note that we use the latest tag, just like we did previously by using the
develop branch.
see https://github.com/trustlines-network/relay/issues/166
> use docker images in docker/trustlines

- .dockerignore
- .travis.yml
- .travis/push-docker-image
- Dockerfile
We use build stages, so that we have a chance to hide our DOCKER_PASSWORD.
The Dockerfile itself now also uses a staged build and copies the virtualenv to
/opt/relay. The base image itself hasn't changed, i.e. I haven't upgraded to
ubuntu 18.04.
The build is pretty much consistent now with what we're doing in the watch and
py-eth-index repositories.
This will also trigger the deploy stage for tags.
> travis: use build stages

- docker/trustlines/README.md
- docker/trustlines/docker-compose.yml
The config files for the relay server have to live in the current directory and
we need to copy the contracts.json from a different path.
> fix docker-compose based setup

- relay/blockchain/currency_network_proxy.py
- relay/relay.py
Read the feeDivisor value from contract when generating network instead of using 100.
Related to https://github.com/trustlines-network/relay/issues/194
> Read the feeDivisor value from contract

- constraints.txt
- tests/chain_integration/test_exchange_proxy.py
When upgrading from solc version 4.21 to 4.25 in the
trustlines-contracts-bin package the exchange tests stopped working.
This is no wonder, because the tests were just wrong. The question
remains, why they were running before even though they were wrong.
> Fix exchange tests

- relay/api/resources.py
- relay/logger.py
Use logging.basicConfig in order to initialize the logging system.
This prevents duplicate log output.
see https://github.com/trustlines-network/relay/issues/203
Also changes back the loggers name in api.resources, that was changed in commit
2fc3928894e831ffe229cf22fa.
> fix duplicate log output bug

- docker/trustlines/README.md
- docker/trustlines/addresses.json
- docker/trustlines/config.json
- docker/trustlines/docker-compose.yml
- docs/RelayServer.md
Change the documentation and the docker-compose example
of the relay server setup to use the trustline blockchain. For the
documentation on how to run the blockchain node itself, we refer to the
documentation in the github repo. The example setup shows how to run the
relay server to work with our predeployed contracts.
Closes #241
> Change documentation and example to use tlbc

- relay/blockchain/proxy.py
CPU usage of the tl-relay server process was too high. The waiting time between
two consecutive requests had been changed from 1.0s to 0.1s in commit
f5001d2416cde863.
We increase the wait time to 1.0s again. This makes CPU usage drop to below 10%.
see https://github.com/trustlines-network/relay/issues/256
> reduce number of requests in watch_filter

- docs/RelayServer.md
- relay/api/resources.py
- relay/blockchain/delegate.py
- tests/chain_integration/test_delegate.py
There is no longer a way for someone to use the relay server as a delegate for a different identity contract not implementing the same nonce/signature and validation mechanism.
We might want to open an issue for creating a parallel API that send meta-transaction with no verifications.
closes https://github.com/trustlines-network/relay/issues/262
> Add basic verification for meta-transaction

- relay/api/messaging/resources.py
- relay/events.py
- relay/network_graph/graph.py
- relay/network_graph/interests.py
- tests/chain_integration/test_graph_integration.py
- tests/unit/network_graph/test_interests.py
- tests/unit/test_streams.py
replaces PR #276 
Remove the usage of time.time() completly from graph to make it not
depending in the time. Also remove time.time() from event creation, the
timestamp has now to be provided.
Changed the default parameter of timestamp from None to 0, so that you
can still not provide it if the timestamp is not relevant. To protect
from accidentially not providing the timestamp when it is relevant, I
added a assertion in the relevant calc interest calculation.
> Remove time.time() from graph

- relay/network_graph/interests.py
- tests/unit/network_graph/test_interests.py
We've had some problems with delta_time getting negative while running the
tests. We now handle a delta_time between -60 and 0 seconds by returning zero
interest.
Please note that I didn't try to find the place where a float is being put into
Account.m_time. That would have been mypy's job.
fixes https://github.com/trustlines-network/relay/issues/279
> allow small negative delta_time during interest_calculation

- config.json
- relay/blockchain/node.py
- relay/relay.py
This is necessary because we had the problem that the rpc call
eth_gasPrice is really slow when the last transaction is a while in
the past.
> Add option to set a fixed gas price suggestion

- relay/network_graph/graph.py
- tests/unit/network_graph/test_graph.py
Remove edge and node from graph if trustlines closed and no longer relevant.
Closes https://github.com/trustlines-protocol/relay/issues/296
> Remove edge and node from graph

- relay/api/resources.py
Fix the path-info endpoint. The missing value needs to be the serialized
value and not the deserialized.
> Fix path-info endpoint when no extraData

- CHANGELOG.rst
Waiting on https://github.com/trustlines-protocol/relay/pull/301 before releasing version 0.7.0
(feel free to modify).
> Update changelog for version 0.7.0

- relay/api/app.py
- relay/api/fields.py
- relay/api/resources.py
Add missing arguments on handle_request_parsing_error to properly handle validation errors on the API
Probably missing as a result of the upgrade of marshmallow
Also adds validation on FeePayerField
See: https://github.com/trustlines-protocol/relay/issues/304 for impact / motivation
> Add missing arguments on handle_request_parsing_error

- CHANGELOG.rst
All tests excepet e2e tests should pass on circle ci. (not merged clientlib yet).
> Update changelog to release 0.8.0

- CHANGELOG.rst
After seeing that we did not release version 0.7.0, squash change log of version 0.8.0 and 0.7.0 to release 0.7.0
> Squash changelog 0.8.0 and 0.7.0

- relay/api/app.py
- relay/api/fields.py
Fix the error that the code expected it to be a string. No correctly
checks first if it is a string.
Also improved the error messages.
Closes #304 
Open issue is that the error message for invalid json is inconsistent since the dependency upgrade. 
I opened an issue #319
> Fix internal server error on HexEncodedBytes

- docs/RelayAPI.md
- relay/api/app.py
- relay/api/resources.py
- relay/main.py
- relay/utils.py
Move get_version from main to utils to avoid circular dependencies
Flake8 would complain if I put the def of get_version before the local imports to avoid circular dependencies and I felt like it did not belong elsewhere
closes https://github.com/trustlines-protocol/relay/issues/317
> Add api to get relay version

- relay/pushservice/client_token_db.py
The ClientTokenDB class could not be used from multiple greenlets
previously. It resulted in the following errors being thrown:
,----
| <class 'sqlalchemy.exc.ProgrammingError'> (psycopg2.ProgrammingError)
| execute cannot be used while an asynchronous query is underway
`----
We now create a sesssion object for each method and make sure it's
lifetime is being handled correctly with a contextmanager.
Also we have seen the following errors on the development server,
see https://github.com/trustlines-network/deployment-config/issues/40:
,----
| sqlalchemy.exc.InvalidRequestError: This Session's transaction has
| been rolled back due to a previous exception during flush. To begin a
| new transaction with this Session, first issue
| Session.rollback(). Original exception
| was: …
> Do not keep the session object alive

- constraints.txt
- relay/api/resources.py
- relay/blockchain/delegate.py
- relay/relay.py
- requirements.txt
- tests/chain_integration/test_delegate.py
Requires the method to deploy a proxied identity in trustlines-contracts-deploy
Does not contain any protection mechanism as to whether the factory/implementation is know to the relay or about the owner.
If the identity is already deployed, the deployment transaction will fail, I try to handle this error but I am not sure that the way I import the error is correct, see: https://github.com/trustlines-protocol/relay/pull/329/files#diff-2b61c07331ed4c639eeadbb73e2dcf8eR9
closes https://github.com/trustlines-protocol/relay/issues/325
> Update endpoint to deploy identity to deploy a proxy

- docs/RelayAPI.md
- relay/api/app.py
- relay/api/resources.py
- relay/blockchain/delegate.py
- relay/relay.py
- tests/chain_integration/test_delegate.py
Give the option to restrict identity deployment to known factories va config
if no config is given, it is unrestricted
WIP: add an endpoint to ask for known identity proxies.
closes: https://github.com/trustlines-protocol/relay/issues/333
Tested via: https://github.com/trustlines-protocol/end2end/compare/test-restricted-factories?expand=1
I am not sure how to make this test clean / whether the test is needed.
> Option to restrict identity deployment to known factories

- CHANGELOG.rst
- relay/relay.py
Remove duplicate logging message from new identity factory that was logged even when no new factory was found.
> Remove duplicate logging message

- config.toml
- relay/relay.py
The clientlib will ask for the currency network of fees and
use it for its meta transaction so it should pass the schema
validation which expect an address / missing
> Change default currency network of fees for delegation to empty

- config.toml
- relay/blockchain/delegate.py
- relay/relay.py
- tests/chain_integration/test_delegate.py
- tests/unit/network_graph/test_graph.py
- tests/unit/network_graph/test_interests.py
(This is based on PR #358, please only review the last commit)
Fix 'from tests' imports
We do not have tests/__init__.py here. Python makes our tests
directory an implicit namespace package iff there is no explicit tests
package on the PYTHONPATH. These 'from tests' imports will not work in
the latter case.
> Fix from tests imports

- config.toml
- relay/blockchain/delegate.py
- relay/relay.py
- tests/chain_integration/test_delegate.py
That's the natural thing to do. We even did that conversion
internally before.
See https://github.com/trustlines-protocol/relay/issues/357
> Declare delegation fees as TOML array of tables in config

- relay/blockchain/currency_network_proxy.py
- tests/chain_integration/test_currency_network.py
Closes: #362
@berndbohmeier @cducrest the output of the failing end-to-end tests look similar to the ones at `master`. I guess that it is broken at the moment and they are "supposed" to fail?
> Remove unused ERC20 functions on currency networks

- requirements.txt
- setup.py
- src/relay/pushservice/pushservice.py
Do not send push notifications twice
We keep a TTL cache of messages already sent and use that to prevent
sending messages twice.
> Dedup push notifications

- constraints.txt
- requirements.txt
- src/relay/relay.py
- src/relay/signing_middleware.py
- tests/unit/test_signing_middleware.py
To make the relay server sign transactions locally, you must configure
the account the be used via a snippet like the following in the TOML
configuration file:
,----
| [relay.account]
| keystore_path = "path/to/keystore.json"
| keystore_password_path = "path/to/passwd.txt"
`----
We use middleware that automatically signs transactions.
This requires the latest contract-deploy-tools.
This is an experimental feature. There might be race conditions with
the nonce handling, because previously we relied on parity to handle
the nonce.
> Make the relay server sign transactions

- config.toml
- constraints.txt
- requirements.txt
- setup.py
- src/relay/main.py
This uses sentry's flask integration for reporting errors to
sentry. THis is a good first start, though we may need more reporting
in case an error doesn't happen during handling of a HTTP request or
we manually return an error code.
See https://github.com/trustlines-protocol/relay/issues/92
> Report errors to sentry

- docs/RelayAPI.md
I forgot to update the api documentation when I changed the schema for the new meta-tx feature. So I do it here.
> Update api documentation for meta-tx schema

- docs/RelayServer.md
Closes: #403
**Note:** This feature is already documented for the docker-compose setup.
> Extend docs for the configuration to sign transactions locally

- docs/RelayServer.md
We should probably document to copy from ./config/, but that PR isn't
merged yet.
> Update docs: create single virtualenv, activate it

- src/relay/relay.py
- src/relay/streams.py
- tests/unit/test_streams.py
Quickfix for the problem that messages are not delivered.
Because we do not send message content anymore over pushnotifications,
pushnotifications should not mark messages as read, so that we can still
read the message later via websockets.
> Pushnotifications do not mark messages as read

- config/addresses_laika.json
We somehow managed to deploy the wrong contracts. The new ones have
been installed with the following packages from PyPI:
,----
| contract-deploy-tools==0.7.1
| trustlines-contracts-bin==1.1.0
| trustlines-contracts-deploy==1.1.0
`----
> Fix identity related addresses on laika

- src/relay/blockchain/currency_network_proxy.py
- src/relay/relay.py
- tests/chain_integration/test_currency_network.py
We were always fetching the users from the chain node when asking for a
network. Make the endpoint faster by using the internal graph representation. This
might be a little outdated, but as we are subscriped to the events it
should only be several seconds old.
We can in the future decide to remove the call to users completly, but i
did not want to add a breaking change now.
Also renamed some methods to make it clearer that they are slow.
> Make /networks endpoint faster

- docs/RelayAPI.md
- src/relay/api/schemas.py
- src/relay/blockchain/events.py
- tests/unit/test_event.py
During the praxis tests we discovered that the pending events where not
received by the mobile app anymore. During the inspection it turned out
that the event identifier calculation fails for pending events. The log
index is `None` and lead to a failure. Unfortunately this did not occur with the
end-to-end tests.
Since the custom event identifier was never finally implemented and was
still under discussion for pending events, the feature has been
postponed. The thought was that the additional response field does not
hurt since it is not used. But because it lead to issues in the staging
setup, we need to revert it here.
This reverts the commits:
- a259d02115059b7e942b5faca56089aa2c732850
- 5d8b99aaa68a21921449dd00cec3a8a1899b4958
> Revert custom event identifier feature

- config.toml
- constraints.txt
- requirements.txt
- src/relay/blockchain/delegate.py
- src/relay/config/schema.py
- src/relay/relay.py
- tests/chain_integration/test_delegate.py
- tests/unit/test_config.py
Closes #434 
Let the delegate specify a gas price strategy in the config.
Three simple strategies were added: rpc, fixed and minmax
Let the delegate also specify the max gas limit
> Make gasprice of delegate transaction configurable

- Dockerfile
Closes: #443
That is the only thing I found where the port is not used/set/exposed/... If that wasn't meant by the feedback please simply comment.
> Expose default relay port for Docker

- docs/RelayAPI.md
- src/relay/api/app.py
- src/relay/api/fields.py
- src/relay/api/resources.py
- src/relay/api/schemas.py
- src/relay/blockchain/delegate.py
- src/relay/relay.py
I don't know if I should use a schema to return the meta transaction status or simply use `MetaTransactionStatusField._serialize` without a schema.
requires: https://github.com/trustlines-protocol/contracts/pull/313
> Meta tx status endpoint

- src/relay/blockchain/currency_network_proxy.py
- src/relay/blockchain/exchange_proxy.py
- src/relay/blockchain/proxy.py
- src/relay/relay.py
- tests/chain_integration/test_currency_network.py
- tests/chain_integration/test_exchange_proxy.py
- tests/chain_integration/test_graph_integration.py
- tests/conftest.py
Before we had one log listener for each event on each contract. Now we
use only 1 log listener for all events. This should boost performance.
I tried to not break too much of the proxy class, so thats why I left
the start_listen.. methods.
Closes #445
> Improve performance of log listener

- src/relay/api/schemas.py
- src/relay/ethindex_db.py
- src/relay/relay.py
The user events endpoint was too slow, as it did a database request per every
currency network separately. This was done because we were to lazy before
to do it properly. This commit improves the situation by using only one
db call for a user event endpoint call. However, the solution is quick
and dirty and we should refactor it in the future.
> Improve performance of user events endpoint

- docs/RelayAPI.md
- src/relay/api/app.py
- src/relay/api/resources.py
- src/relay/network_graph/graph.py
closes: https://github.com/trustlines-protocol/relay/issues/454
Tested manually by running the e2e tests to generate data and querying the endpoint via `curl` which made me realise that we have an additional undocumented field `address` on returned trustlines list: https://github.com/trustlines-protocol/relay/issues/460
> Add endpoint for getting the list of trustlines for a network

- src/relay/blockchain/events_informations.py
- src/relay/blockchain/proxy.py
- src/relay/ethindex_db.py
This fixes a bug where the relay would not be able to get transfer
details for meta-transactions since they have DebtUpdate events in the
eth-index db and these have no corresponding event builders.
(I guess mypy helped me this time)
> Only get transfer and balance update events from tx for transfer details

- src/relay/blockchain/events.py
Block_hash should be optional HexBytes since it can be none in certain
situations
> Fix type error for blockchain events for block_hash

- .pre-commit-config.yaml
I could not find an issue with a reason why we did not do that, but maybe there is one.
> Add mypy pre-commit hook

- docs/RelayAPI.md
- src/relay/api/app.py
- src/relay/api/resources.py
- src/relay/blockchain/currency_network_events.py
- src/relay/blockchain/currency_network_proxy.py
- src/relay/blockchain/events_informations.py
- src/relay/ethindex_db.py
- src/relay/relay.py
- tests/chain_integration/test_currency_network.py
Add an endpoint to query for the events of a trustlines. This includes
all relevent events, including the Balance update events, as they should
here be interesting.
closes #470
> Add trustline events endpoint

- src/relay/api/schemas.py
- src/relay/blockchain/events.py
- src/relay/blockchain/events_informations.py
- src/relay/pushservice/pushservice.py
Add transactionHash to rest endpoints. transactionId is kept for
backwardscompatibilty but will be removed in the future.
> Deprecate transactionId for transactionHash

- src/relay/api/resources.py
- src/relay/blockchain/events_informations.py
- tests/chain_integration/test_event_information.py
Allows to look up transfer details based on any involved event.
Refactor finding of Balanceupdate events to not go many times over the
array.
Closes #467
> Add lookup of transfer details by balance update

- src/relay/api/fields.py
- src/relay/api/resources.py
- src/relay/api/schemas.py
Fix the validation so that it can also handle 0 as logIndex. Before this
was not possible, because 0 will be evaluated as False. The correct way
is to check not None instead.
Also check now that logIndex is a positive number and hash has the
correct format.
> Fix validation of transfer endpoint

- src/relay/api/exchange/resources.py
- src/relay/api/resources.py
- src/relay/blockchain/events_informations.py
- src/relay/ethindex_db.py
- src/relay/relay.py
Based on: https://github.com/trustlines-protocol/relay/pull/495
I found it hard to make refactoring that was straight improvement. I hope I did the most that is not so opinionated.
I thought about removing `address` from EthindexDB because it is confusing as to which method will use a default address for filtering, but I did not think it was an obvious improvement since then all methods using the default address will need to have it as a non-optional parameter.
I had the choice to remove all `get_ethindex_db_for_...` functions and have specific classes for each contracts that inherit `EthindexDB` with static `standard_event_types`, `from_to_types` and `event_builders`,  as it is the main difference in between each of these functions. I thought that was not obviously better.
I think …
> Refactor ethindex

- tests/tlclient.py
Add a small test script that can be used to test the performance of
endpoints. In this case it is used to test the performance of the
transfer details endpoint.
> Add performance test script for transfer details

- CHANGELOG.rst
- src/relay/pushservice/pushservice.py
See https://firebase.google.com/docs/reference/admin/python/firebase_admin.exceptions for NotFoundError
Also check the issue https://github.com/firebase/firebase-admin-python/issues/180
> Catch firebase error for when client token is not found

- docs/RelayAPI.md
- src/relay/api/resources.py
- src/relay/ethindex_db/ethindex_db.py
- src/relay/relay.py
It was documented to provide events for currency networks, but was
actually returning events for any contracts (exchange, tokens ...)
Closes https://github.com/trustlines-protocol/relay/issues/502
> Enhance endpoint for user events to add filtering by contract type

- dev-requirements.txt
- requirements.txt
- src/relay/blockchain/proxy.py
- src/relay/web3provider.py
Have to upgrade web3 to make it work with new version of contract deploy tools.
With upgrading, the signature of `get_event_data` changed, even though it is a minor upgrade. After looking into it, I see that `get_event_data` is not part of the public api of web3, it is a `_utils` function and should not be used. I use a work around to replace it.
If you need me to explain it, we can jump on a call.
> Update web3 to 5.7.0 to be compatible with new contract deploy tools

- src/relay/api/resources.py
We were returning an empty list object when there was no accrued
interests with the friend of a user, return none instead
> Remove empty interests from endpoint of accured interest for user

- .circleci/config.yml
The tests are now failing due to the limit in new contracts version of interest to 20% and the fact that the old tests use 300% interests.
See the fail here: https://github.com/trustlines-protocol/relay/pull/549
> Update backwards compatibility test with new clientlib version

- src/relay/blockchain/proxy.py
This potentially prevent informing users about two events in the wrong order
closes https://github.com/trustlines-protocol/relay/issues/553
> Sort events we get from filters

- .circleci/config.yml
- Dockerfile
- dev-requirements.txt
- requirements.txt
- setup.py
- src/relay/main.py
Requires https://github.com/trustlines-protocol/end2end/pull/37 (right now it points to this branch in the circleci config, but once merged I'll point back to master)
You can see the new fancy coverage report there: https://codecov.io/gh/trustlines-protocol/relay/list/592316de12e346ede03f56514e23ca1f4c6bc2df/
> Report e2e tests code coverage

- README.rst
That would prevent us from uploading the new relay version to pypi
> The hyperlinks in the readme were wrongly formatted

- CHANGELOG.rst
- dev-requirements.in
- dev-requirements.txt
- requirements.txt
- setup.py
- src/relay/blockchain/currency_network_proxy.py
- src/relay/ethindex_db/sync_updates.py
- src/relay/network_graph/graph.py
- src/relay/relay.py
- tests/chain_integration/conftest.py
- tests/chain_integration/database_integration/test_graph_sync.py
- tests/chain_integration/test_currency_network.py
No longer uses filters to update proxy on is_frozen status of graph
Filters should not update the state of currency networks and leave
that task to ethindex.
Requires ethindex >= 0.3.5
also requires new version of contracts for testing with `NetworkUnfreeze` event
> Use ethindex to update is_frozen status on graph

- src/relay/ethindex_db/ethindex_db.py
--- Logging error ---
Traceback (most recent call last):
File "/opt/relay/lib/python3.8/site-packages/flask_sockets.py", line 40, in __call__
handler, values = adapter.match()
File "/opt/relay/lib/python3.8/site-packages/werkzeug/routing.py", line 1799, in match
raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.8/logging/__init__.py", line 1081, in emit
msg = self.format(record)
File "/usr/lib/python3.8/logging/__init__.py", line 925, in format
return fmt.format(record)
File "/usr/lib/python3.8/logging/__init__.py", line 664, in …
> Fix relay crash due to wrong logger arguments

- tests/chain_integration/conftest.py
- tests/chain_integration/database_integration/conftest.py
- tests/chain_integration/database_integration/test_graph_sync.py
- tests/chain_integration/test_currency_network.py
- tests/chain_integration/test_delegate.py
The tests now use the v2 of the network instead of `TestCurrencyNetwork`
so they lack the function of freezing / unfreezing a network and setting
trustlines for users.
A test currency network fixture was added for the few remaining test
that need it.
> Update tests that were failing due to removal of test network

- .circleci/config.yml
- tests/chain_integration/database_integration/conftest.py
This speeds up tests using the indexer a lot.
This should also make them non-flaky as the tests won't have to
wait for as long for the indexer to sync.
> Lower indexer required confirmation in tests to 50

- .circleci/config.yml
The test was broken when we changed the returned list of accrued
interests to remove null values.
Pray for all tests to succeed.
> Upgrade the version of the clientlib in backwards compatibility test

- CHANGELOG.rst
- config.toml
- src/relay/web3provider.py
It was broken due to conflict in between asyncio and gevent
closes https://github.com/trustlines-protocol/relay/issues/580
> Drop support for websockets
